<template><div><h1 id="roller" tabindex="-1"><a class="header-anchor" href="#roller"><span>Roller</span></a></h1>
<p><strong>Roller</strong> kısmından yeni dinamik roller eklemektir. Bu aşamada, <strong>ID</strong>, <strong>alan</strong> ve <strong>harita</strong> kısımları doldurulur. Harita kısmında, veri tanımlarında kaydedilen bilgilere göre aşağıdaki gibi bir kod yazılır:</p>
<p><img src="/TimyaBPM-Documents/roller1.png" alt="alt text"></p>
<div class="language-csharp line-numbers-mode" data-highlighter="prismjs" data-ext="cs" data-title="cs"><pre v-pre class="language-csharp"><code><span class="line"><span class="token class-name"><span class="token keyword">object</span></span> ilgiliKisi <span class="token operator">=</span> <span class="token function">getVal</span><span class="token punctuation">(</span><span class="token string">"GelenEvrak"</span><span class="token punctuation">,</span> <span class="token string">"IlgiliKisi"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">if</span> <span class="token punctuation">(</span>ilgiliKisi <span class="token operator">==</span> <span class="token keyword">null</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">return</span> System<span class="token punctuation">.</span>Convert<span class="token punctuation">.</span><span class="token function">ToInt32</span><span class="token punctuation">(</span>ilgiliKisi<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">else</span></span>
<span class="line">    <span class="token keyword">return</span> <span class="token number">1</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token class-name">Daha</span> sonra<span class="token punctuation">,</span> süreç kısmındaki <span class="token string">"To-Do List"</span> bölümünde roller kısmında tanımlanan kısım seçilir ve <span class="token string">"Form List"</span> kısmından oluşturulan form seçilir<span class="token punctuation">.</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


